# Generated by Django 2.2.12 on 2021-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localityDescription',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('MSSubClass', models.IntegerField()),
                ('MSZoning', models.CharField(default='', max_length=21)),
                ('LotFrontage', models.IntegerField()),
                ('LotArea', models.IntegerField()),
                ('Street', models.CharField(default='', max_length=21)),
                ('Alley', models.CharField(default='', max_length=21)),
                ('LotShape', models.CharField(default='', max_length=21)),
                ('LandContour', models.CharField(default='', max_length=21)),
                ('Utilities', models.CharField(default='', max_length=21)),
                ('LotConfig', models.CharField(default='', max_length=21)),
                ('LandSlope', models.CharField(default='', max_length=21)),
                ('Neighborhood', models.CharField(default='', max_length=21)),
            ],
        ),
    ]
